CONNECT TO DATA;

DROP TABLE REPORT.ACCOUTMERGE;
DROP TABLE REPORT.TRANSACTIONS;
DROP TABLE REPORT.TICKETFORM;
DROP TABLE REPORT.FORBIDDENUSERS;
DROP TABLE REPORT.NONTICKETFORM;
DROP TABLE REPORT.ESCALATIONFORM;
DROP TABLE REPORT.PARATURE;
DROP TABLE REPORT.OTHERFORM;

CREATE TABLE REPORT.ACCOUTMERGE(PACCOUNT VARCHAR(200) NOT NULL, ACCOUNT VARCHAR(200) NOT NULL,REGION VARCHAR(10) NOT NULL, PRIMARY KEY(PACCOUNT));

CREATE TABLE REPORT.TRANSACTIONS(CID VARCHAR(200) NOT NULL, ACTIONBY VARCHAR(200) NOT NULL,ACTIONTIME DATE NOT NULL,ACTION VARCHAR(200) NOT NULL,DESCRIPTION VARCHAR(200), PRIMARY KEY(CID));

CREATE TABLE REPORT.TICKETFORM(CID VARCHAR(1000) NOT NULL, APPRECIATED_USERID VARCHAR(2000) NOT NULL, APPRECIATED_USERNAME VARCHAR(2000) NOT NULL, REASON VARCHAR(2000), CLIENT VARCHAR(1000) NOT NULL, TDATE DATE NOT NULL,FUNCTIONAL_TEAM VARCHAR(200) ,TICKET_CATEGORY VARCHAR(200) NOT NULL,RATINGTYPE VARCHAR(200) NOT NULL,SEVERITY VARCHAR(100) NOT NULL,STATE VARCHAR(2000),STATUS VARCHAR(100) NOT NULL,TICKETNO VARCHAR(2000) NOT NULL, TYPE VARCHAR(100) NOT NULL, USERID VARCHAR(500) NOT NULL,USERNAME VARCHAR(500) NOT NULL,APPRECIATION_TEXT VARCHAR(4000),FEEDBACK VARCHAR(4000), PRIMARY KEY(CID));

CREATE TABLE REPORT.FORBIDDENUSERS(USERID VARCHAR(100) NOT NULL, PRIMARY KEY(USERID));

CREATE TABLE REPORT.NONTICKETFORM( ID VARCHAR(100) NOT NULL, APPRECIATED_USERID VARCHAR(100) NOT NULL,APPRECIATED_USERNAME VARCHAR(100) NOT NULL,APPRTXT VARCHAR(1000) NOT NULL, CLIENT VARCHAR(100) NOT NULL, TDATE DATE NOT NULL, FUNCTIONAL_TEAM VARCHAR(100) NOT NULL,APPRECIATED_BY VARCHAR(100) NOT NULL ,REASON VARCHAR(100), STATUS VARCHAR(10) NOT NULL, TYPE VARCHAR(100) NOT NULL, USERID VARCHAR(100) NOT NULL,USERNAME VARCHAR(100) NOT NULL , PRIMARY KEY(ID));

CREATE TABLE REPORT.ESCALATIONFORM( ID VARCHAR(200) NOT NULL, ESCALATED_USERID VARCHAR(200) NOT NULL,ESCALATED_USERNAME VARCHAR(200) NOT NULL, ESCALATION_TEXT VARCHAR(2000) NOT NULL, CLIENT VARCHAR(200) NOT NULL, DATE_OF_REPORT DATE NOT NULL,DATE_OF_RESOLUTION DATE, FUNCTIONAL_TEAM VARCHAR(100), IBMISSUE VARCHAR(10) NOT NULL, ESCALATION_RAISED_BY VARCHAR(100) NOT NULL, SEVERITY VARCHAR(10) NOT NULL,TICKETNO VARCHAR(100) ,TICKET_CATEGORY VARCHAR(100), TYPE VARCHAR(20) NOT NULL, USERID VARCHAR(200) NOT NULL,USERNAME VARCHAR(200) NOT NULL,ACTION_TAKEN VARCHAR(2000), PRIMARY KEY(ID));

CREATE TABLE REPORT.OTHERFORM( ID VARCHAR(100) NOT NULL, APPRECIATED_USERID VARCHAR(100) NOT NULL,APPRECIATED_USERNAME VARCHAR(100) NOT NULL,APPRTXT VARCHAR(1000) NOT NULL, OTHER VARCHAR(100) NOT NULL, TDATE DATE NOT NULL, FUNCTIONAL_TEAM VARCHAR(100) NOT NULL,APPRECIATED_BY VARCHAR(100) NOT NULL ,REASON VARCHAR(100), STATUS VARCHAR(10) NOT NULL, TYPE VARCHAR(100) NOT NULL, USERID VARCHAR(100) NOT NULL,USERNAME VARCHAR(100) NOT NULL , PRIMARY KEY(ID));

CREATE TABLE REPORT.PARATURE(CID VARCHAR(100) NOT NULL, PARATURE_NAME VARCHAR(200) NOT NULL, LDAP_NAME VARCHAR(200) NOT NULL,IBM_INTRANET_ID VARCHAR(100) NOT NULL, PRIMARY KEY(CID));
